Update cd.yml

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -25,6 +25,15 @@ jobs:
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
+          
+      - name: Check files before Docker build
+        run: |
+          echo "Current directory:"
+          pwd
+          echo "Files in current directory:"
+          ls -l
+          echo "Files in app folder:"
+          ls -l app || echo "app folder not found"
 
       # 3️⃣ Docker 이미지 빌드 및 푸시
       - name: Build and Push Docker image
